version: '3'
services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
    depends_on:
      - db

  db:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./data/db:/data/db